---
- name: Converge
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Ensure upower is installed
      ansible.builtin.package:
        name: upower

    - name: Set upower charge thresholds
      ansible.builtin.import_role:
        name: egdoc.upower_charge_thresholds
